this.examples=[
	{
		"name": "Uni-Menschen",
		"description": "Ein einfaches Beispiel.",
		"source": "&Uml;bung zur Vorlesung",
		"ruleset": [
			"@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .",
			"@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .",
			"@prefix foaf: <http://xmlns.com/foaf/0.1/> .",
			"<#SOKRATES>",
			"    a foaf:Person ;",
			"    foaf:firstName \"Sokrates\" ;",
			"    foaf:surName \"Sokrates\" ;",
			"    foaf:name \"Sokrates\" ;",
			"    foaf:age 30 ;",
			"    foaf:knows [",
			"        a foaf:Person ;",
			"        foaf:name \"Russel\"",
			"    ];",
			"    foaf:knows [",
			"        a foaf:Person ;",
			"        foaf:name \"MCurie\"",
			"    ] .",
			"<#MCURIE>",
			"    a foaf:Person ;",
			"    foaf:firstName \"Marie\" ;",
			"    foaf:name \"MCurie\" ;",
			"    foaf:SurName \"Curie\" ;",
			"    foaf:age 29 ;",
			"    foaf:knows [",
			"        a foaf:Person ;",
			"        foaf:name \"PCurie\"",
			"    ];",
			"    foaf:knows [",
			"        a foaf:Person ;",
			"        foaf:name \"Russel\"",
			"    ];",
			"    foaf:knows [",
			"        a foaf:Person ;",
			"        foaf:name \"Sokrates\"",
			"    ] .",
			"<#PCURIE>",
			"    a foaf:Person ;",
			"    foaf:firstName \"Pierre\" ;",
			"    foaf:name \"PCurie\" ;",
			"    foaf:SurName \"Curie\" ;",
			"    foaf:age 29 ;",
			"    foaf:knows [",
			"        a foaf:Person ;",
			"        foaf:name \"MCurie\"",
			"    ] .",
			"<#RUSSEL>",
			"    a foaf:Person ;",
			"    foaf:firstName \"Bertrand\" ;",
			"    foaf:name \"Russel\" ;",
			"    foaf:SurName \"Russel\" ;",
			"    foaf:age 97 ;",
			"    foaf:knows [",
			"        a foaf:Person ;",
			"        foaf:name \"Sokrates\"",
			"    ] ."
		],
		"query": "PREFIX foaf: <http://xmlns.com/foaf/0.1/> SELECT ?name2 WHERE { ?person1 foaf:knows ?person2. ?person1 foaf:firstName \"Sokrates\" .?person2 foaf:name ?name2 .}"
	}
]
