this.examples=[
	{
		"name": "Uni-Menschen",
		"description": "Ein einfaches Beispiel.",
		"source": "&Uml;bung zur Vorlesung",
		"ruleset": [
			"@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .",
			"@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .",
			"@prefix foaf: <http://xmlns.com/foaf/0.1/> .",
			"<#SOKRATES>",
			"    a foaf:Person ;",
			"    foaf:firstName \"Sokrates\" ;",
			"    foaf:surName \"Sokrates\" ;",
			"    foaf:name \"Sokrates\" ;",
			"    foaf:age 30 ;",
			"    foaf:knows [",
			"        a foaf:Person ;",
			"        foaf:name \"Russel\"",
			"    ];",
			"    foaf:knows [",
			"        a foaf:Person ;",
			"        foaf:name \"MCurie\"",
			"    ] .",
			"<#MCURIE>",
			"    a foaf:Person ;",
			"    foaf:firstName \"Marie\" ;",
			"    foaf:name \"MCurie\" ;",
			"    foaf:SurName \"Curie\" ;",
			"    foaf:age 29 ;",
			"    foaf:knows [",
			"        a foaf:Person ;",
			"        foaf:name \"PCurie\"",
			"    ];",
			"    foaf:knows [",
			"        a foaf:Person ;",
			"        foaf:name \"Russel\"",
			"    ];",
			"    foaf:knows [",
			"        a foaf:Person ;",
			"        foaf:name \"Sokrates\"",
			"    ] .",
			"<#PCURIE>",
			"    a foaf:Person ;",
			"    foaf:firstName \"Pierre\" ;",
			"    foaf:name \"PCurie\" ;",
			"    foaf:SurName \"Curie\" ;",
			"    foaf:age 29 ;",
			"    foaf:knows [",
			"        a foaf:Person ;",
			"        foaf:name \"MCurie\"",
			"    ] .",
			"<#RUSSEL>",
			"    a foaf:Person ;",
			"    foaf:firstName \"Bertrand\" ;",
			"    foaf:name \"Russel\" ;",
			"    foaf:SurName \"Russel\" ;",
			"    foaf:age 97 ;",
			"    foaf:knows [",
			"        a foaf:Person ;",
			"        foaf:name \"Sokrates\"",
			"    ] ."
		],
		"query": "PREFIX foaf: <http://xmlns.com/foaf/0.1/> SELECT ?name2 WHERE { ?person1 foaf:knows ?person2. ?person1 foaf:firstName \"Sokrates\" .?person2 foaf:name ?name2 .}"
	},
	{
		"name": "Märchen",
		"description": "Märchen über Märchen.",
		"source": "&Uml;bung zur Vorlesung",
		"ruleset": [
                     "@prefix ex: <http://example.org/>.",
                     "ex:Rapunzel ex:hatAutor ex:Sokrates.",
                     "ex:Rapunzel ex:erschienen 2006.",
                     "ex:Aschenputtel ex:hatAutor ex:Archimedes.",
                     "ex:Aschenputtel ex:hatAutor ex:Platon.",
                     "ex:Schneewittchen ex:hatAutor ex:Platon.",
                     "ex:Schneewittchen ex:erschienen 2004."
		],
		"query": "PREFIX ex: <http://example.org/> SELECT ?book ?jahr WHERE { ?book ex:erschienen ?jahr .}"
	},
	{
		"name": "Märchenbücher",
		"description": "Märchen über Märchen.",
		"source": "&Uml;bung zur Vorlesung",
		"ruleset": [
                     "@prefix ex:<http://maerchen.example.org/>.",
                     "ex:KHG1 ex:hatAutor ex:Grimm.",
                     "ex:KHG1 ex:erschienen 1812.",
                     "ex:Rapunzel ex:teilVon ex:KHG1.",
                     "ex:DerGestiefelteKater ex:teilVon ex:KHG1.",
                     "ex:KHG2 ex:hatAutor ex:Grimm.",
                     "ex:KHG2 ex:erschienen 1837.",
                     "ex:SchneeweißchenUndRosenrot ex:teilVon ex:KHG2.",
                     "ex:Kindermaerchen ex:hatAutor ex:Anderson.",
                     "ex:Kindermaerchen ex:erschienen 1837.",
                     "ex:KleineMeerjungfrau ex:teilVon ex:Kindermaerchen."
		],
		"query": "PREFIX ex:<http://maerchen.example.org/> SELECT ?book WHERE {?book ex:hatAutor ex:Grimm. ?book ex:erschienen ?jahr FILTER (?jahr > 1836).}"
	}
]
